### ISSUE TITLE
install to root path

### ISSUE THREAD

**Issue by boredsquirrel** [trytomakeyouprivate/COPR-command#1]
`/root/.local/bin` does not exist, installing the command will likely need RPM packaging

**Comment by Malix-Labs** [comment]
I think it would be nice to have RPM packaging indeed, as it would be the only package needed anyway

In the meantime, I think it would be nice to have it publish it as a COPR package, as the last COPR package ever needed, along with a copy-paste script to install it

**Comment by boredsquirrel** [comment]
hi there!

I am actually not that sure about the need of this. it works rootless, and users should not use a root account. I will close this issue.
