### ISSUE TITLE
Use `find` instead of `ls`

### ISSUE THREAD

**Issue by fiftydinar** [trytomakeyouprivate/COPR-command#2]
Instead of

`ls /etc/yum.repos.d/ | grep COPR_`

Use

`find /etc/yum.repos.d/ -type f -name 'COPR_*' -printf "%f\n"`

`find` is more reliable, as it's strictly used for finding files like in this example with additional options & it's better for further parsing the output, while classic `ls` is usually used to list folder content & nothing else by the ordinary user.

**Comment by fiftydinar** [comment]
Also, `_copr_` filename is used by `dnf copr enable` instead of current `COPR_`

**Comment by boredsquirrel** [comment]
good tip, will use that. tbh I dont like the _copr_ name but will change to match upstream
