### ISSUE TITLE
Support Instruction

### ISSUE THREAD

**Issue by Malix-Labs** [trytomakeyouprivate/COPR-command#4]
Hey,

This project is great.

Can you provide a documentation about how we can help you make it implemented, at least in concept, in `rpm-ostree` as [you apparently already have been told that](https://discussion.fedoraproject.org/t/how-to-use-copr-on-fedora-atomic/106067/5
) ?

For example, some links to GitHub / fedora / redhat issues we can subscribe to and upvote

**Comment by boredsquirrel** [comment]
Hey sorry for the incredibly late reply. I get too much Github spam...

I see no reason to add it to rpm-ostree. It works, is easy to understand and Fedora will switch to dnf and OCI containers in like 2 releases.

I could absolutely learn Rust and rewrite this into a real languge. But when Fedora switches to dnf (again) then the functionality is already included.

Even though I prefer some of my commands tbh, but some like search are just a workaround.

**Comment by Malix-Labs** [comment]
> sorry for the incredibly late reply

No worries :smile:

> Fedora will switch to dnf

Could you link some references about that? I had no idea

> Even though I prefer some of my commands tbh, but some like search are just a workaround

Did you thought about a pull request to DNF to make some of your ideas and implementation be reviewed?

**Comment by boredsquirrel** [comment]
https://fedoraproject.org/wiki/Changes/OstreeNativeContainerStable

Very interesting read. I still dont get the "why", but I suppose
- use dnf only
- allow easier building of containers
- remove ostree, just containers, less technology
- make it easier for users

The switch will be done with F41 it seems, with a systemd unit that rebases to the ostree native container image.

**Comment by Malix-Labs** [comment]
Nice, thanks !

> remove ostree

It seems that OSTree will still be used in the backend
